export enum ROUTES {
  HOME = '/',
  CHAT = '/chat',
  AUTH = '/authentication',
  FORGOT_PASSWORD = '/forgot-password',
  TOOLS = '/tools',
  SETTING = '/settings',
  CHECKOUT = '/checkout',
  REALTIME_TRANSLATOR = '/realtime-translator',
  IMAGE_GENERATOR = '/ImageCreator',
  SOCIAL_CONNECTION = '/social-connection',
  HELP = '/help',
  ACCOUNT = '/account',
  SUBSCRIPTION = '/subscription',
  // CHECKOUT = '/checkout',
}
