import { Email, HeadPhone, Help, Info, Phone, Shield } from 'assets/svgs';

export type SettingsItem = {
  icon: () => JSX.Element;
  title: ScreenName | string;
  hasMore?: boolean;
};

export enum ScreenName {
  SETTINGS = 'Settings',
  FAQS = 'FAQs',
  GET_HELP = 'Get Help',
  TERMS_OF_SERVICE = 'Terms of Service',
  PRIVACY_POLICY = 'Privacy Policy',
}

export const Screens = [
  ScreenName.SETTINGS,
  ScreenName.FAQS,
  ScreenName.GET_HELP,
  ScreenName.TERMS_OF_SERVICE,
  ScreenName.PRIVACY_POLICY,
];

export const helpAndSupportItems: Array<SettingsItem> = [
  {
    icon: Help,
    title: ScreenName.FAQS,
    hasMore: true,
  },
  {
    icon: HeadPhone,
    title: ScreenName.GET_HELP,
    hasMore: true,
  },
  {
    icon: Info,
    title: ScreenName.TERMS_OF_SERVICE,
    hasMore: true,
  },
  {
    icon: Shield,
    title: ScreenName.PRIVACY_POLICY,
    hasMore: true,
  },
];

export const FAQItems = [
  {
    question: 'Can I try Adamo before committing to a paid plan?',
    answer:
      'Yes, we offer a free plan with limited access to AI capabilities. This plan is a great way to test the platform and see if it meets your needs before upgrading to a paid plan.',
  },
  {
    question: 'Can I upgrade or downgrade my plan at any time?',
    answer: '',
  },
  {
    question: 'Is the Chat AI App available in different languages?',
    answer: '',
  },
  {
    question: 'What kinds of questions can I ask the Chat AI App?',
    answer: '',
  },
];

export const contactDetails: Array<SettingsItem> = [
  {
    icon: Email,
    title: 'adamo@gmail.com',
  },
  {
    icon: Phone,
    title: '1-800-555-5555',
  },
];

export const termsOfServices = {
  date: 'June 25, 2023',
  disclaimer:
    'Please read these Terms of Use ("Terms") carefully before using the Adamo AI Chat mobile application ("App"). These Terms govern your access to and use of the App, including any content, functionality, and services provided through the App.',
  details: [
    'Acceptance of Terms By downloading, installing, or using the Adamo AI Chat App, you agree to be bound by these Terms and our Privacy Policy. If you do not agree with any part of these Terms, please refrain from using the App.',
    'User Eligibility You must be at least 18 years old or have reached the age of majority in your jurisdiction to use the App. By using the App, you represent and warrant that you meet these age requirements.',
    'Nature of the App The Adamo AI Chat App is an artificial intelligence-powered chat application that provides automated responses and conversations. Please note that the responses generated by the App may not always be accurate or appropriate. The App is not intended to replace professional advice or human interaction.',
    "User Conduct When using the Adamo AI Chat App, you agree to: a. Use the App for lawful purposes only and not engage in any illegal activities. b. Respect the intellectual property rights of others and not infringe upon them. c. Refrain from transmitting any harmful or malicious code to the App. d. Not attempt to access or interfere with the App's underlying systems or security measures. e. Use the App responsibly and not engage in any activity that may disrupt or hinder its operation.",
    'Privacy We are committed to protecting your privacy. Our Privacy Policy explains how we collect, use, and disclose information from users of the App. By using the App, you consent to our collection and use of personal information as outlined in the Privacy Policy.',
    'Disclaimer of Liability The Adamo AI Chat App is provided on an "as is" and "as available" basis. We do not warrant the accuracy, completeness, or reliability of the App\'s responses or content. Your use of the App is at your own risk, and we disclaim all liabilities arising from any reliance on the App or its responses.',
    'Limitation of Liability To the extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with the use of the App or these Terms, even if we have been advised of the possibility of such damages. In no event shall our total liability exceed the amount you paid, if any, for accessing the App.',
    'Intellectual Property The App and all its content, including but not limited to text, graphics, logos, images, and software, are the property of Adamo or its licensors and are protected by intellectual property laws. You agree not to modify, distribute, reproduce, or create derivative works based on the App or its content without our prior written consent.',
    'Modification and Termination We reserve the right to modify or terminate the App or these Terms at any time, for any reason, without prior notice. You are responsible for regularly reviewing the most current version of these Terms. Your continued use of the App after any modifications to the Terms constitutes acceptance of such changes.',
    'Governing Law and Jurisdiction These Terms shall be governed by and construed in accordance with the laws of [Jurisdiction]. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of [Jurisdiction].',
  ],
  endDiscliamer:
    'By using the Adamo AI Chat App, you acknowledge that you have read, understood, and agreed to these Terms.',
};

export const PrivacyPolicy = {
  date: 'June 25, 2023',
  disclaimer:
    'This Privacy Policy ("Policy") explains how Adamo AI Chat ("we," "us," or "our") collects, uses, and protects the personal information of users ("you" or "your") when you use the Adamo AI Chat mobile application ("App"). This Policy applies to the information collected through the App and its related services.',
  details: [
    {
      title: 'Information We Collect',
      points: [
        'a. Personal Information: We may collect personal information that you voluntarily provide when using the App, such as your name, email address, and any other information you choose to provide.',
        'b. Usage Information: We may collect information about your interactions with the App, including log files, app usage data, and device information (e.g., device type, operating system, unique device identifiers).',
        "c. Chat Data: When you engage in conversations or interact with the App, we may collect and retain the content of those communications for the purpose of improving the App's functionality and performance.",
      ],
    },
    {
      title: 'Use of Information',
      points: [
        "a. Provide and Improve the App: We may use the collected information to provide you with the App's services, personalize your experience, improve the App's features, and develop new functionalities.",
        'b. Communication: We may use your contact information to respond to your inquiries, provide support, and communicate important notices regarding the App.',
        "c. Analytics and Research: We may use aggregated and anonymized data for analytical purposes, such as understanding user behavior, trends, and preferences, to enhance the App's performance and user experience.",
        'd. Legal Compliance: We may process and disclose your information as required by applicable laws, regulations, or legal proceedings.',
      ],
    },
    {
      title: 'Data Sharing and Disclosure',
      points: [
        'a. Service Providers: We may engage trusted third-party service providers to assist us in providing and maintaining the App. These providers may have access to your personal information for the sole purpose of performing their services on our behalf.',
        'b. Compliance with Law: We may disclose your information if required by law, legal process, or governmental request, or to protect our rights, privacy, safety, or property, or that of others.',
        'c. Business Transfers: In the event of a merger, acquisition, or sale of all or a portion of our assets, your information may be transferred to the acquiring entity.',
      ],
    },
    {
      title: 'Data Security',
      points: [
        'We take reasonable measures to protect your information from unauthorized access, disclosure, alteration, or destruction. However, please be aware that no security measures are perfect or impenetrable, and we cannot guarantee the absolute security of your information.',
      ],
    },
    {
      title: 'Third-Party Links and Services',
      points: [
        'The App may contain links to third-party websites or services that are not controlled or operated by us. This Privacy Policy does not apply to such third-party services, and we are not responsible for their privacy practices. We encourage you to review the privacy policies of these third parties before providing any personal information.',
      ],
    },
    {
      title: "Children's Privacy",
      points: [
        'The Adamo AI Chat App is not intended for use by individuals under the age of 18. We do not knowingly collect personal information from children. If you become aware that your child has provided us with personal information without your consent, please contact us, and we will promptly delete such information from our systems.',
      ],
    },
    {
      title: 'Changes to this Privacy Policy',
      points: [
        'We may update this Privacy Policy from time to time. Any changes will be effective immediately upon posting the revised Policy in the App. We encourage you to review this Policy periodically to stay informed about how we collect, use, and protect your information.',
      ],
    },
    {
      title: 'Contact Us',
      points: [
        "If you have any questions, concerns, or requests regarding this Privacy Policy or the App's privacy practices, please contact us at adamo.ai",
      ],
    },
  ],
};
