import { Email, HeadPhone, Help, Info, Phone, Shield } from 'assets/svgs';

export type SettingsItem = {
  icon: () => JSX.Element;
  title: ScreenName | string;
  hasMore?: boolean;
};

export enum ScreenName {
  SETTINGS = 'Settings',
  FAQS = 'FAQs',
  GET_HELP = 'Get Help',
  TERMS_OF_SERVICE = 'Terms of Service',
  PRIVACY_POLICY = 'Privacy Policy',
}

export const Screens = [
  ScreenName.SETTINGS,
  ScreenName.FAQS,
  ScreenName.GET_HELP,
  ScreenName.TERMS_OF_SERVICE,
  ScreenName.PRIVACY_POLICY,
];

export const helpAndSupportItems: Array<SettingsItem> = [
  {
    icon: Help,
    title: ScreenName.FAQS,
    hasMore: true,
  },
  {
    icon: HeadPhone,
    title: ScreenName.GET_HELP,
    hasMore: true,
  },
  {
    icon: Info,
    title: ScreenName.TERMS_OF_SERVICE,
    hasMore: true,
  },
  {
    icon: Shield,
    title: ScreenName.PRIVACY_POLICY,
    hasMore: true,
  },
];

export const FAQItems = [
  {
    question: 'Can I try Adamo before committing to a paid plan?',
    answer:
      'Yes, we offer a free plan with limited access to AI capabilities. This plan is a great way to test the platform and see if it meets your needs before upgrading to a paid plan.',
  },
  {
    question: 'Can I upgrade or downgrade my plan at any time?',
    answer: '',
  },
  {
    question: 'Is the Chat AI App available in different languages?',
    answer: '',
  },
  {
    question: 'What kinds of questions can I ask the Chat AI App?',
    answer: '',
  },
];

export const contactDetails: Array<SettingsItem> = [
  {
    icon: Email,
    title: 'adamo@gmail.com',
  },
  {
    icon: Phone,
    title: '1-800-555-5555',
  },
];

export const termsOfServices = {
  date: 'June 25, 2023',
  disclaimer:
    'Please read these Terms of Use ("Terms") carefully before using the Adamo AI Chat mobile application ("App"). These Terms govern your access to and use of the App, including any content, functionality, and services provided through the App.',
  details: [
    'Acceptance of Terms By downloading, installing, or using the Adamo AI Chat App, you agree to be bound by these Terms and our Privacy Policy. If you do not agree with any part of these Terms, please refrain from using the App.',
    'User Eligibility You must be at least 18 years old or have reached the age of majority in your jurisdiction to use the App. By using the App, you represent and warrant that you meet these age requirements.',
    'Nature of the App The Adamo AI Chat App is an artificial intelligence-powered chat application that provides automated responses and conversations. Please note that the responses generated by the App may not always be accurate or appropriate. The App is not intended to replace professional advice or human interaction.',
    "User Conduct When using the Adamo AI Chat App, you agree to: a. Use the App for lawful purposes only and not engage in any illegal activities. b. Respect the intellectual property rights of others and not infringe upon them. c. Refrain from transmitting any harmful or malicious code to the App. d. Not attempt to access or interfere with the App's underlying systems or security measures. e. Use the App responsibly and not engage in any activity that may disrupt or hinder its operation.",
    'Privacy We are committed to protecting your privacy. Our Privacy Policy explains how we collect, use, and disclose information from users of the App. By using the App, you consent to our collection and use of personal information as outlined in the Privacy Policy.',
    'Disclaimer of Liability The Adamo AI Chat App is provided on an "as is" and "as available" basis. We do not warrant the accuracy, completeness, or reliability of the App\'s responses or content. Your use of the App is at your own risk, and we disclaim all liabilities arising from any reliance on the App or its responses.',
    'Limitation of Liability To the extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with the use of the App or these Terms, even if we have been advised of the possibility of such damages. In no event shall our total liability exceed the amount you paid, if any, for accessing the App.',
    'Intellectual Property The App and all its content, including but not limited to text, graphics, logos, images, and software, are the property of Adamo or its licensors and are protected by intellectual property laws. You agree not to modify, distribute, reproduce, or create derivative works based on the App or its content without our prior written consent.',
    'Modification and Termination We reserve the right to modify or terminate the App or these Terms at any time, for any reason, without prior notice. You are responsible for regularly reviewing the most current version of these Terms. Your continued use of the App after any modifications to the Terms constitutes acceptance of such changes.',
    'Governing Law and Jurisdiction These Terms shall be governed by and construed in accordance with the laws of [Jurisdiction]. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of [Jurisdiction].',
  ],
  endDiscliamer:
    'By using the Adamo AI Chat App, you acknowledge that you have read, understood, and agreed to these Terms.',
};
